create table if not exists public.leaderboard_scores (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 20),
  wave integer not null default 0,
  kills integer not null default 0,
  money integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.leaderboard_scores enable row level security;

drop policy if exists "leaderboard read" on public.leaderboard_scores;
create policy "leaderboard read"
on public.leaderboard_scores
for select
using (true);

drop policy if exists "leaderboard insert" on public.leaderboard_scores;
create policy "leaderboard insert"
on public.leaderboard_scores
for insert
to anon
with check (true);
